name: practice
version: '1.0-SNAPSHOT'
main: org.nseu.practice.Main
api-version: '1.21'
authors: [ nseuseng ]
description: Practice Plugin
website: nseu.org
commands:
  대전:
    description: 대전 명령어
  파티:
    description: 파티 명령어

