name: PracticeCore
version: '1.0-SNAPSHOT'
main: org.nseu.practice.Main
api-version: '1.21.1'
authors: [ nseuseng ]
description: Practice Plugin
commands:
  대전:
    description:
  파티:
    description:
  관전:
    description:
  아레나:
    description:
  킷:
    description: